# Generated by Django 3.2.12 on 2022-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IWD_Homes', '0002_IWD_Homes'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='disability',
            field=models.CharField(choices=[('ADHD', 'Attention Deficit Hyperactivity Disorder (ADHD)'), ('LD', 'Learning Disabilities'), ('MD', 'Mobility Disabilities'), ('MedD', 'Medical Disabilities'), ('PsyD', 'Psychiatric Disabilities'), ('PTSD', 'Traumatic Brain Injury (TBI) and Post-Traumatic Stress Disorder (PTSD)'), ('VD', 'Visual Impairments'), ('DF', 'Deaf and Hard of Hearing'), ('ASD', 'Autism Spectrum Disorders'), ('O', 'Other')], default='O', max_length=6),
        ),
        migrations.AddField(
            model_name='host',
            name='other',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disability',
            field=models.CharField(choices=[('ADHD', 'Attention Deficit Hyperactivity Disorder (ADHD)'), ('LD', 'Learning Disabilities'), ('MD', 'Mobility Disabilities'), ('MedD', 'Medical Disabilities'), ('PsyD', 'Psychiatric Disabilities'), ('PTSD', 'Traumatic Brain Injury (TBI) and Post-Traumatic Stress Disorder (PTSD)'), ('VD', 'Visual Impairments'), ('DF', 'Deaf and Hard of Hearing'), ('ASD', 'Autism Spectrum Disorders'), ('O', 'Other')], default='O', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='other',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
