# Generated by Django 3.2.12 on 2022-03-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IWD_Homes', '0003_auto_20220305_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
