# Generated by Django 3.2.12 on 2022-03-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IWD_Homes', '0004_auto_20220305_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
