# Generated by Django 3.2.12 on 2022-03-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IWD_Homes', '0010_auto_20220306_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='disability',
            field=models.CharField(choices=[('Attention Deficit Hyperactivity Disorder (ADHD)', 'Attention Deficit Hyperactivity Disorder (ADHD) '), ('Learning Disabilities', 'Learning Disabilities '), ('Mobility Disabilities', 'Mobility Disabilities '), ('Medical Disabilities', 'Medical Disabilities '), ('Psychiatric Disabilities', 'Psychiatric Disabilities '), ('Traumatic Brain Injury (TBI) and Post-Traumatic Stress Disorder (PTSD)', 'Traumatic Brain Injury (TBI) and Post-Traumatic Stress Disorder (PTSD) '), ('Visual Impairments', 'Visual Impairments '), ('Deaf and Hard of Hearing', 'Deaf and Hard of Hearing '), ('Autism Spectrum Disorders', 'Autism Spectrum Disorders '), ('Other', 'Other ')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='disability',
            field=models.CharField(choices=[('Attention Deficit Hyperactivity Disorder (ADHD)', 'Attention Deficit Hyperactivity Disorder (ADHD) '), ('Learning Disabilities', 'Learning Disabilities '), ('Mobility Disabilities', 'Mobility Disabilities '), ('Medical Disabilities', 'Medical Disabilities '), ('Psychiatric Disabilities', 'Psychiatric Disabilities '), ('Traumatic Brain Injury (TBI) and Post-Traumatic Stress Disorder (PTSD)', 'Traumatic Brain Injury (TBI) and Post-Traumatic Stress Disorder (PTSD) '), ('Visual Impairments', 'Visual Impairments '), ('Deaf and Hard of Hearing', 'Deaf and Hard of Hearing '), ('Autism Spectrum Disorders', 'Autism Spectrum Disorders '), ('Other', 'Other ')], default='Other', max_length=100),
        ),
    ]
