# Generated by Django 3.2.12 on 2022-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IWD_Homes', '0012_auto_20220306_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='family_number',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
